---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux



steps:
- name: Start syncing && Compiling
  environment: 
    TELEGRAM_TOKEN: 
      from_secret: BOT_API_KEY
  image: brock5555/recovery
  commands:
  - bash build.sh
